name: backend services development workflow

on:
  push:
    branches:
      - main
      - master

jobs:
  development-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: First CI/CD step
        run: echo "Hello world"
